function [fitresult, gof] = generate_luca(xdata, ydata, zdata)
%CREATEFIT(XDATA,YDATA,ZDATA)
%  Create a fit.
%
%  Data for 'luca' fit:
%      X Input : xdata
%      Y Input : ydata
%      Z Output: zdata
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Mar-2022 20:59:37


%% Fit: 'luca'.
[xData, yData, zData] = prepareSurfaceData( xdata, ydata, zdata );

% Set up fittype and options.
ft = 'cubicinterp';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'luca' );
h = plot( fitresult, [xData, yData], zData );
% Label axes
xlabel( '$\frac{h}{b}$', 'Interpreter', 'latex' );
ylabel( '$\frac{t_{s}}{t}$', 'Interpreter', 'latex' );
zlabel( 'K', 'Interpreter', 'latex' );
grid on


